sudo: required

services:
  - docker
  - mongodb
env:
  global:
    - IMAGENAME=virgil-auth
language: go

go:
  - 1.7.x

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - ./build/go-get-virgil-crypto.sh

install:
  - go get -t -u ./...

before_script:
  - echo $TRAVIS_COMMIT $TRAVIS_BRANCH
  - time docker build -t $IMAGENAME --build-arg GIT_COMMIT=$TRAVIS_COMMIT --build-arg GIT_BRANCH=$TRAVIS_BRANCH  -f build/Dockerfile .
  - docker images
  - docker inspect -f '{{index .ContainerConfig.Labels "git-commit"}}' $IMAGENAME
  - docker inspect -f '{{index .ContainerConfig.Labels "git-branch"}}' $IMAGENAME
  - docker tag $IMAGENAME-$TRAVIS_BRANCH virgilsecurity-docker-core.bintray.io/services/$IMAGENAME-$TRAVIS_BRANCH:latest;
  - docker tag $IMAGENAME-$TRAVIS_BRANCH virgilsecurity-docker-core.bintray.io/services/$IMAGENAME-$TRAVIS_BRANCH:$TRAVIS_COMMIT;


script:
  - DB=127.0.0.1:27017 go test ./... -tags=integration
  - go build -v --ldflags '-extldflags "-static"' -o main
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" virgilsecurity-docker-core.bintray.io;
  - docker push virgilsecurity-docker-core.bintray.io/services/$IMAGENAME-$TRAVIS_BRANCH:latest;
  - docker push virgilsecurity-docker-core.bintray.io/services/$IMAGENAME-$TRAVIS_BRANCH:$TRAVIS_COMMIT;

after_seccess:
  - echo virgilsecurity-docker-core.bintray.io/services/$IMAGENAME-$TRAVIS_BRANCH:$TRAVIS_COMMIT;

branches:
  only:
  - master
  - /^v\/d+$/
